//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subs.XMLServiceTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOTP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.SendOTPResponse SendOTP(Subs.XMLServiceTest.ServiceReference1.SendOTPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOTP", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.SendOTPResponse> SendOTPAsync(Subs.XMLServiceTest.ServiceReference1.SendOTPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorize", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.AuthorizeResponse Authorize(Subs.XMLServiceTest.ServiceReference1.AuthorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorize", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.AuthorizeResponse> AuthorizeAsync(Subs.XMLServiceTest.ServiceReference1.AuthorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorizations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.AuthorizationsResponse Authorizations(Subs.XMLServiceTest.ServiceReference1.AuthorizationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorizations", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.AuthorizationsResponse> AuthorizationsAsync(Subs.XMLServiceTest.ServiceReference1.AuthorizationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEMailByCustomerId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdResponse FindEMailByCustomerId(Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEMailByCustomerId", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdResponse> FindEMailByCustomerIdAsync(Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomerIdByEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailResponse FindCustomerIdByEmail(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomerIdByEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailResponse> FindCustomerIdByEmailAsync(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomerIdByNationalId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdResponse FindCustomerIdByNationalId(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCustomerIdByNationalId", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdResponse> FindCustomerIdByNationalIdAsync(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDeliveryAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.InsertDeliveryAddressResponse InsertDeliveryAddress(Subs.XMLServiceTest.ServiceReference1.InsertDeliveryAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDeliveryAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.InsertDeliveryAddressResponse> InsertDeliveryAddressAsync(Subs.XMLServiceTest.ServiceReference1.InsertDeliveryAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveryAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.GetDeliveryAddressResponse GetDeliveryAddress(Subs.XMLServiceTest.ServiceReference1.GetDeliveryAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveryAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.GetDeliveryAddressResponse> GetDeliveryAddressAsync(Subs.XMLServiceTest.ServiceReference1.GetDeliveryAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDeliveryAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseModel))]
        Subs.XMLServiceTest.ServiceReference1.UpdateDeliveryAddressResponse UpdateDeliveryAddress(Subs.XMLServiceTest.ServiceReference1.UpdateDeliveryAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDeliveryAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.UpdateDeliveryAddressResponse> UpdateDeliveryAddressAsync(Subs.XMLServiceTest.ServiceReference1.UpdateDeliveryAddressRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string sourceField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeliveryAddressData2))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DeliveryAddressData2 : BaseModel {
        
        private int deliveryAddressIdField;
        
        private string phoneNumberField;
        
        private int countryIdField;
        
        private string provinceField;
        
        private string cityField;
        
        private string suburbField;
        
        private string streetField;
        
        private string streetExtensionField;
        
        private string streetSuffixField;
        
        private System.Nullable<int> streetIdField;
        
        private string streetNoField;
        
        private string buildingField;
        
        private string floorNoField;
        
        private string roomField;
        
        private string postCodeField;
        
        private string sDIField;
        
        private string modifiedByField;
        
        private System.DateTime modifiedOnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DeliveryAddressId {
            get {
                return this.deliveryAddressIdField;
            }
            set {
                this.deliveryAddressIdField = value;
                this.RaisePropertyChanged("DeliveryAddressId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CountryId {
            get {
                return this.countryIdField;
            }
            set {
                this.countryIdField = value;
                this.RaisePropertyChanged("CountryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
                this.RaisePropertyChanged("Province");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Suburb {
            get {
                return this.suburbField;
            }
            set {
                this.suburbField = value;
                this.RaisePropertyChanged("Suburb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string StreetExtension {
            get {
                return this.streetExtensionField;
            }
            set {
                this.streetExtensionField = value;
                this.RaisePropertyChanged("StreetExtension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string StreetSuffix {
            get {
                return this.streetSuffixField;
            }
            set {
                this.streetSuffixField = value;
                this.RaisePropertyChanged("StreetSuffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> StreetId {
            get {
                return this.streetIdField;
            }
            set {
                this.streetIdField = value;
                this.RaisePropertyChanged("StreetId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string StreetNo {
            get {
                return this.streetNoField;
            }
            set {
                this.streetNoField = value;
                this.RaisePropertyChanged("StreetNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
                this.RaisePropertyChanged("Building");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string FloorNo {
            get {
                return this.floorNoField;
            }
            set {
                this.floorNoField = value;
                this.RaisePropertyChanged("FloorNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
                this.RaisePropertyChanged("Room");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
                this.RaisePropertyChanged("PostCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string SDI {
            get {
                return this.sDIField;
            }
            set {
                this.sDIField = value;
                this.RaisePropertyChanged("SDI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public System.DateTime ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizationResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int yearField;
        
        private int monthField;
        
        private int customerIdField;
        
        private int productIdField;
        
        private int seatsField;
        
        private System.DateTime expirationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
                this.RaisePropertyChanged("Month");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("ProductId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Seats {
            get {
                return this.seatsField;
            }
            set {
                this.seatsField = value;
                this.RaisePropertyChanged("Seats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SeatResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int seatsField;
        
        private string reasonField;
        
        private System.DateTime expirationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Seats {
            get {
                return this.seatsField;
            }
            set {
                this.seatsField = value;
                this.RaisePropertyChanged("Seats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendOTP", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendOTPRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pCustomerId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pOTP;
        
        public SendOTPRequest() {
        }
        
        public SendOTPRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, int pCustomerId, int pOTP) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pCustomerId = pCustomerId;
            this.pOTP = pOTP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendOTPResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendOTPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SendOTPResult;
        
        public SendOTPResponse() {
        }
        
        public SendOTPResponse(bool SendOTPResult) {
            this.SendOTPResult = SendOTPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Authorize", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pProductId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pReceiverId;
        
        public AuthorizeRequest() {
        }
        
        public AuthorizeRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, int pProductId, int pReceiverId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pProductId = pProductId;
            this.pReceiverId = pReceiverId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Subs.XMLServiceTest.ServiceReference1.SeatResult AuthorizeResult;
        
        public AuthorizeResponse() {
        }
        
        public AuthorizeResponse(Subs.XMLServiceTest.ServiceReference1.SeatResult AuthorizeResult) {
            this.AuthorizeResult = AuthorizeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Authorizations", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizationsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        public AuthorizationsRequest() {
        }
        
        public AuthorizationsRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader) {
            this.AuthorizationHeader = AuthorizationHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizationsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationResult[] AuthorizationsResult;
        
        public AuthorizationsResponse() {
        }
        
        public AuthorizationsResponse(Subs.XMLServiceTest.ServiceReference1.AuthorizationResult[] AuthorizationsResult) {
            this.AuthorizationsResult = AuthorizationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindEMailByCustomerId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindEMailByCustomerIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pCustomerId;
        
        public FindEMailByCustomerIdRequest() {
        }
        
        public FindEMailByCustomerIdRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, int pCustomerId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pCustomerId = pCustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindEMailByCustomerIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindEMailByCustomerIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool FindEMailByCustomerIdResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pEmailAddress;
        
        public FindEMailByCustomerIdResponse() {
        }
        
        public FindEMailByCustomerIdResponse(bool FindEMailByCustomerIdResult, string pEmailAddress) {
            this.FindEMailByCustomerIdResult = FindEMailByCustomerIdResult;
            this.pEmailAddress = pEmailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCustomerIdByEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindCustomerIdByEmailRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string EmailAddress;
        
        public FindCustomerIdByEmailRequest() {
        }
        
        public FindCustomerIdByEmailRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, string EmailAddress) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.EmailAddress = EmailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCustomerIdByEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindCustomerIdByEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool FindCustomerIdByEmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int CustomerId;
        
        public FindCustomerIdByEmailResponse() {
        }
        
        public FindCustomerIdByEmailResponse(bool FindCustomerIdByEmailResult, int CustomerId) {
            this.FindCustomerIdByEmailResult = FindCustomerIdByEmailResult;
            this.CustomerId = CustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCustomerIdByNationalId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindCustomerIdByNationalIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string NationalId;
        
        public FindCustomerIdByNationalIdRequest() {
        }
        
        public FindCustomerIdByNationalIdRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, string NationalId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.NationalId = NationalId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCustomerIdByNationalIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindCustomerIdByNationalIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool FindCustomerIdByNationalIdResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int CustomerId;
        
        public FindCustomerIdByNationalIdResponse() {
        }
        
        public FindCustomerIdByNationalIdResponse(bool FindCustomerIdByNationalIdResult, int CustomerId) {
            this.FindCustomerIdByNationalIdResult = FindCustomerIdByNationalIdResult;
            this.CustomerId = CustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertDeliveryAddress", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertDeliveryAddressRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pCustomerId;
        
        public InsertDeliveryAddressRequest() {
        }
        
        public InsertDeliveryAddressRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData, int pCustomerId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pDeliveryAddressData = pDeliveryAddressData;
            this.pCustomerId = pCustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertDeliveryAddressResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertDeliveryAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string InsertDeliveryAddressResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData;
        
        public InsertDeliveryAddressResponse() {
        }
        
        public InsertDeliveryAddressResponse(string InsertDeliveryAddressResult, Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData) {
            this.InsertDeliveryAddressResult = InsertDeliveryAddressResult;
            this.pDeliveryAddressData = pDeliveryAddressData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeliveryAddress", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDeliveryAddressRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pDeliveryAddressId;
        
        public GetDeliveryAddressRequest() {
        }
        
        public GetDeliveryAddressRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, int pDeliveryAddressId) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pDeliveryAddressId = pDeliveryAddressId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeliveryAddressResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDeliveryAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetDeliveryAddressResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData;
        
        public GetDeliveryAddressResponse() {
        }
        
        public GetDeliveryAddressResponse(string GetDeliveryAddressResult, Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData) {
            this.GetDeliveryAddressResult = GetDeliveryAddressResult;
            this.pDeliveryAddressData = pDeliveryAddressData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDeliveryAddress", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateDeliveryAddressRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData;
        
        public UpdateDeliveryAddressRequest() {
        }
        
        public UpdateDeliveryAddressRequest(Subs.XMLServiceTest.ServiceReference1.AuthorizationHeader AuthorizationHeader, Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData) {
            this.AuthorizationHeader = AuthorizationHeader;
            this.pDeliveryAddressData = pDeliveryAddressData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDeliveryAddressResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateDeliveryAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UpdateDeliveryAddressResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData;
        
        public UpdateDeliveryAddressResponse() {
        }
        
        public UpdateDeliveryAddressResponse(string UpdateDeliveryAddressResult, Subs.XMLServiceTest.ServiceReference1.DeliveryAddressData2 pDeliveryAddressData) {
            this.UpdateDeliveryAddressResult = UpdateDeliveryAddressResult;
            this.pDeliveryAddressData = pDeliveryAddressData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Subs.XMLServiceTest.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Subs.XMLServiceTest.ServiceReference1.ServiceSoap>, Subs.XMLServiceTest.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Subs.XMLServiceTest.ServiceReference1.SendOTPResponse SendOTP(Subs.XMLServiceTest.ServiceReference1.SendOTPRequest request) {
            return base.Channel.SendOTP(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.SendOTPResponse> SendOTPAsync(Subs.XMLServiceTest.ServiceReference1.SendOTPRequest request) {
            return base.Channel.SendOTPAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.AuthorizeResponse Authorize(Subs.XMLServiceTest.ServiceReference1.AuthorizeRequest request) {
            return base.Channel.Authorize(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.AuthorizeResponse> AuthorizeAsync(Subs.XMLServiceTest.ServiceReference1.AuthorizeRequest request) {
            return base.Channel.AuthorizeAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.AuthorizationsResponse Authorizations(Subs.XMLServiceTest.ServiceReference1.AuthorizationsRequest request) {
            return base.Channel.Authorizations(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.AuthorizationsResponse> AuthorizationsAsync(Subs.XMLServiceTest.ServiceReference1.AuthorizationsRequest request) {
            return base.Channel.AuthorizationsAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdResponse FindEMailByCustomerId(Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdRequest request) {
            return base.Channel.FindEMailByCustomerId(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdResponse> FindEMailByCustomerIdAsync(Subs.XMLServiceTest.ServiceReference1.FindEMailByCustomerIdRequest request) {
            return base.Channel.FindEMailByCustomerIdAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailResponse FindCustomerIdByEmail(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailRequest request) {
            return base.Channel.FindCustomerIdByEmail(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailResponse> FindCustomerIdByEmailAsync(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByEmailRequest request) {
            return base.Channel.FindCustomerIdByEmailAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdResponse FindCustomerIdByNationalId(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdRequest request) {
            return base.Channel.FindCustomerIdByNationalId(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdResponse> FindCustomerIdByNationalIdAsync(Subs.XMLServiceTest.ServiceReference1.FindCustomerIdByNationalIdRequest request) {
            return base.Channel.FindCustomerIdByNationalIdAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.InsertDeliveryAddressResponse InsertDeliveryAddress(Subs.XMLServiceTest.ServiceReference1.InsertDeliveryAddressRequest request) {
            return base.Channel.InsertDeliveryAddress(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.InsertDeliveryAddressResponse> InsertDeliveryAddressAsync(Subs.XMLServiceTest.ServiceReference1.InsertDeliveryAddressRequest request) {
            return base.Channel.InsertDeliveryAddressAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.GetDeliveryAddressResponse GetDeliveryAddress(Subs.XMLServiceTest.ServiceReference1.GetDeliveryAddressRequest request) {
            return base.Channel.GetDeliveryAddress(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.GetDeliveryAddressResponse> GetDeliveryAddressAsync(Subs.XMLServiceTest.ServiceReference1.GetDeliveryAddressRequest request) {
            return base.Channel.GetDeliveryAddressAsync(request);
        }
        
        public Subs.XMLServiceTest.ServiceReference1.UpdateDeliveryAddressResponse UpdateDeliveryAddress(Subs.XMLServiceTest.ServiceReference1.UpdateDeliveryAddressRequest request) {
            return base.Channel.UpdateDeliveryAddress(request);
        }
        
        public System.Threading.Tasks.Task<Subs.XMLServiceTest.ServiceReference1.UpdateDeliveryAddressResponse> UpdateDeliveryAddressAsync(Subs.XMLServiceTest.ServiceReference1.UpdateDeliveryAddressRequest request) {
            return base.Channel.UpdateDeliveryAddressAsync(request);
        }
    }
}
